"""Write a self-contained `preview.html` so the output can be screenshotted.

Vanilla HTML + CSS, no build step, no network. The page puts the GIF (or MP4)
inside a macOS-style window frame on a dark backdrop and lists the caption
chapters underneath - which is exactly the shape of a good LinkedIn image.
"""

import os

PAGE = u"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s — reel preview</title>
<style>
  :root {
    --bg: #0a0c11;
    --panel: #12151d;
    --line: #232834;
    --text: #e8ecf4;
    --muted: #8b95a8;
    --accent: #2ee6c5;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    background:
      radial-gradient(1100px 620px at 50%% -12%%, #1b2130 0%%, rgba(10,12,17,0) 62%%),
      var(--bg);
    color: var(--text);
    font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    min-height: 100vh;
    display: flex;
    justify-content: center;
    padding: 56px 24px 72px;
  }
  .wrap { width: 100%%; max-width: %(maxw)dpx; }
  .brand {
    display: flex; align-items: center; gap: 10px;
    font-size: 13px; letter-spacing: .14em; text-transform: uppercase;
    color: var(--muted); margin-bottom: 18px;
  }
  .brand b { color: var(--accent); font-weight: 700; letter-spacing: .1em; }
  h1 { font-size: 26px; line-height: 1.25; margin: 0 0 8px; font-weight: 650; letter-spacing: -.01em; }
  .sub { color: var(--muted); margin: 0 0 28px; font-size: 14px; }
  .sub span { color: var(--text); }
  .dot { color: var(--line); margin: 0 8px; }

  .frame {
    border-radius: 14px;
    background: var(--panel);
    border: 1px solid var(--line);
    box-shadow:
      0 1px 0 rgba(255,255,255,.04) inset,
      0 28px 60px -20px rgba(0,0,0,.85),
      0 8px 20px -12px rgba(0,0,0,.6);
    overflow: hidden;
  }
  .chrome {
    display: flex; align-items: center; gap: 7px;
    padding: 11px 14px;
    background: linear-gradient(#171b25, #12151d);
    border-bottom: 1px solid var(--line);
  }
  .chrome i { width: 11px; height: 11px; border-radius: 50%%; display: block; }
  .chrome i:nth-child(1) { background: #ff5f57; }
  .chrome i:nth-child(2) { background: #febc2e; }
  .chrome i:nth-child(3) { background: #28c840; }
  .chrome small { margin-left: 10px; color: var(--muted); font-size: 12px; }
  .stage { display: block; background: #05070a; }
  .stage img, .stage video { display: block; width: 100%%; height: auto; }

  .meta {
    display: flex; flex-wrap: wrap; gap: 10px;
    margin: 20px 0 0;
  }
  .pill {
    border: 1px solid var(--line); border-radius: 999px;
    padding: 6px 13px; font-size: 12.5px; color: var(--muted);
    background: rgba(255,255,255,.015);
  }
  .pill b { color: var(--text); font-weight: 600; }

  h2 {
    font-size: 12px; letter-spacing: .14em; text-transform: uppercase;
    color: var(--muted); margin: 34px 0 12px; font-weight: 600;
  }
  ol { list-style: none; margin: 0; padding: 0; }
  li {
    display: flex; gap: 16px; align-items: baseline;
    padding: 11px 2px; border-top: 1px solid var(--line);
  }
  li:last-child { border-bottom: 1px solid var(--line); }
  li time {
    font: 600 13px/1 ui-monospace, SFMono-Regular, Menlo, monospace;
    color: var(--accent); min-width: 54px;
  }
  footer { margin-top: 34px; color: var(--muted); font-size: 12.5px; }
  footer code { color: var(--text); background: rgba(255,255,255,.05);
    padding: 2px 6px; border-radius: 5px; font-size: 12px; }
</style>
</head>
<body>
  <div class="wrap">
    <div class="brand"><b>▌ reel</b> <span>demo preview</span></div>
    <h1>%(title)s</h1>
    <p class="sub">%(subtitle)s</p>

    <div class="frame">
      <div class="chrome"><i></i><i></i><i></i><small>%(filename)s</small></div>
      <div class="stage">%(media)s</div>
    </div>

    <div class="meta">%(pills)s</div>
%(chapters)s
    <footer>Generated by <code>reel</code>. Open this file in a browser and screenshot the frame.</footer>
  </div>
</body>
</html>
"""


def esc(text):
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _media_tag(filename):
    lower = filename.lower()
    if lower.endswith((".mp4", ".mov", ".m4v", ".webm")):
        return (
            '<video src="%s" autoplay loop muted playsinline></video>' % esc(filename)
        )
    return '<img src="%s" alt="demo">' % esc(filename)


def build_page(filename, title=None, pills=(), chapters=(), subtitle=None, max_width=940):
    """Pure: -> the full HTML document as a string."""
    pill_html = "".join(
        '<span class="pill">%s <b>%s</b></span>' % (esc(k), esc(v)) for k, v in pills
    )
    if chapters:
        items = "".join(
            "      <li><time>%s</time><span>%s</span></li>\n" % (esc(t), esc(text))
            for t, text in chapters
        )
        chapter_html = '    <h2>Chapters</h2>\n    <ol>\n%s    </ol>\n' % items
    else:
        chapter_html = ""
    return PAGE % {
        "title": esc(title or os.path.basename(filename)),
        "subtitle": esc(subtitle or "Trimmed, sped up and palette-optimised from a raw screen recording."),
        "filename": esc(os.path.basename(filename)),
        "media": _media_tag(os.path.basename(filename)),
        "pills": pill_html,
        "chapters": chapter_html,
        "maxw": int(max_width),
    }


def write_preview(media_path, out_path=None, title=None, pills=(), chapters=(),
                  subtitle=None, max_width=940):
    """Write preview.html next to `media_path` and return its path."""
    media_path = os.path.abspath(media_path)
    if out_path is None:
        out_path = os.path.join(os.path.dirname(media_path) or ".", "preview.html")
    html = build_page(
        os.path.basename(media_path), title, pills, chapters, subtitle, max_width
    )
    with open(out_path, "w") as fh:
        fh.write(html)
    return out_path
